"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['main_app.py']
DATA_FILES = []
OPTIONS = {'argv_emulation': True,
           'iconfile': 'sr.icns',
           'packages': ['PySide2']}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app', 'shiboken2', 'PySide2', 'cffi', 'Pillow'],
)
